name: CI/CD Pipeline

on:
  push:
    branches: [master]

jobs:
  basic-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Клонування репозиторію
        uses: actions/checkout@v4

      - name: Встановлення Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Встановлення залежностей
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Запуск тестів
        run: pytest

  build:
    runs-on: ubuntu-latest
    needs: basic-checks
    steps:
      - name: Клонування репозиторію
        uses: actions/checkout@v4

      - name: Побудова Docker-образу
        run: docker build -t my-python-app .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Симуляція розгортання
        run: |
          echo "Гілка: ${{ github.ref_name }}"
          echo "Коміт: ${{ github.sha }}"
          echo "Автор: ${{ github.actor }}"
          echo "Розгортання завершено"

  notify:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - name: Надсилання Telegram повідомлення
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="CI/CD pipeline завершено. Статус: УСПІШНО ✅"
